#!/usr/bin/env bash
set -euo pipefail
ROOT=$(cd "$(dirname "$0")/.." && pwd)
source "$ROOT/version.env"
OUTPUT="$ROOT/Sources/imsg/Version.swift"
mkdir -p "$(dirname "$OUTPUT")"
cat > "$OUTPUT" <<SWIFT
// Generated by scripts/generate-version.sh. Do not edit.
enum IMsgVersion {
  static let current = "${MARKETING_VERSION}"
}
SWIFT
